FROM mambaorg/micromamba:1.5.6
COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml /tmp/env.yaml
RUN micromamba install --yes --file /tmp/env.yaml && \
	micromamba clean --all --yes
ARG MAMBA_DOCKERFILE_ACTIVATE=1